

// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var matchResponse = MatchResponse.FromJson(jsonString);

namespace FriendsTracker.Components.Infrastructure;

using System;
using System.Collections.Generic;

using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

public partial class MatchResponse
{
    [JsonProperty("status")]
    public long Status { get; set; }

    [JsonProperty("data")]
    public Datum[] Data { get; set; }
}

public partial class Datum
{
    [JsonProperty("is_available")]
    public bool IsAvailable { get; set; }

    [JsonProperty("metadata")]
    public Metadata Metadata { get; set; }

    [JsonProperty("players")]
    public Players Players { get; set; }

    [JsonProperty("observers")]
    public object[] Observers { get; set; }

    [JsonProperty("coaches")]
    public object[] Coaches { get; set; }

    [JsonProperty("teams")]
    public Teams Teams { get; set; }

    [JsonProperty("rounds")]
    public Round[] Rounds { get; set; }

    [JsonProperty("kills")]
    public Kill[] Kills { get; set; }
}

public partial class Kill
{
    [JsonProperty("kill_time_in_round")]
    public long KillTimeInRound { get; set; }

    [JsonProperty("kill_time_in_match")]
    public long KillTimeInMatch { get; set; }

    [JsonProperty("round", NullValueHandling = NullValueHandling.Ignore)]
    public long? Round { get; set; }

    [JsonProperty("killer_puuid")]
    public Guid KillerPuuid { get; set; }

    [JsonProperty("killer_display_name")]
    public string KillerDisplayName { get; set; }

    [JsonProperty("killer_team")]
    public string KillerTeam { get; set; }

    [JsonProperty("victim_puuid")]
    public Guid VictimPuuid { get; set; }

    [JsonProperty("victim_display_name")]
    public string VictimDisplayName { get; set; }

    [JsonProperty("victim_team")]
    public string VictimTeam { get; set; }

    [JsonProperty("victim_death_location")]
    public Location VictimDeathLocation { get; set; }

    [JsonProperty("damage_weapon_id")]
    public string DamageWeaponId { get; set; }

    [JsonProperty("damage_weapon_name")]
    public string DamageWeaponName { get; set; }

    [JsonProperty("damage_weapon_assets")]
    public DamageWeaponAssetsClass DamageWeaponAssets { get; set; }

    [JsonProperty("secondary_fire_mode")]
    public bool SecondaryFireMode { get; set; }

    [JsonProperty("player_locations_on_kill")]
    public PlayerLocationsOn[] PlayerLocationsOnKill { get; set; }

    [JsonProperty("assistants")]
    public Assistant[] Assistants { get; set; }
}

public partial class Assistant
{
    [JsonProperty("assistant_puuid")]
    public Guid AssistantPuuid { get; set; }

    [JsonProperty("assistant_display_name")]
    public string AssistantDisplayName { get; set; }

    [JsonProperty("assistant_team")]
    public string AssistantTeam { get; set; }
}

public partial class DamageWeaponAssetsClass
{
    [JsonProperty("display_icon")]
    public Uri DisplayIcon { get; set; }

    [JsonProperty("killfeed_icon")]
    public Uri KillfeedIcon { get; set; }
}

public partial class PlayerLocationsOn
{
    [JsonProperty("player_puuid")]
    public Guid PlayerPuuid { get; set; }

    [JsonProperty("player_display_name")]
    public string PlayerDisplayName { get; set; }

    [JsonProperty("player_team")]
    public string PlayerTeam { get; set; }

    [JsonProperty("location")]
    public Location Location { get; set; }

    [JsonProperty("view_radians")]
    public double ViewRadians { get; set; }
}

public partial class Location
{
    [JsonProperty("x")]
    public long X { get; set; }

    [JsonProperty("y")]
    public long Y { get; set; }
}

public partial class Metadata
{
    [JsonProperty("map")]
    public string Map { get; set; }

    [JsonProperty("game_version")]
    public string GameVersion { get; set; }

    [JsonProperty("game_length")]
    public long GameLength { get; set; }

    [JsonProperty("game_start")]
    public long GameStart { get; set; }

    [JsonProperty("game_start_patched")]
    public string GameStartPatched { get; set; }

    [JsonProperty("rounds_played")]
    public long RoundsPlayed { get; set; }

    [JsonProperty("mode")]
    public string Mode { get; set; }

    [JsonProperty("mode_id")]
    public string ModeId { get; set; }

    [JsonProperty("queue")]
    public string Queue { get; set; }

    [JsonProperty("season_id")]
    public Guid SeasonId { get; set; }

    [JsonProperty("platform")]
    public string Platform { get; set; }

    [JsonProperty("matchid")]
    public Guid Matchid { get; set; }

    [JsonProperty("premier_info")]
    public PremierInfo PremierInfo { get; set; }

    [JsonProperty("region")]
    public string Region { get; set; }

    [JsonProperty("cluster")]
    public string Cluster { get; set; }
}

public partial class PremierInfo
{
    [JsonProperty("tournament_id")]
    public object TournamentId { get; set; }

    [JsonProperty("matchup_id")]
    public object MatchupId { get; set; }
}

public partial class Players
{
    [JsonProperty("all_players")]
    public AllPlayer[] AllPlayers { get; set; }

    [JsonProperty("red")]
    public AllPlayer[] Red { get; set; }

    [JsonProperty("blue")]
    public AllPlayer[] Blue { get; set; }
}

public partial class AllPlayer
{
    [JsonProperty("puuid")]
    public Guid Puuid { get; set; }

    [JsonProperty("name")]
    public string Name { get; set; }

    [JsonProperty("tag")]
    public string Tag { get; set; }

    [JsonProperty("team")]
    public string Team { get; set; }

    [JsonProperty("level")]
    public long Level { get; set; }

    [JsonProperty("character")]
    public string Character { get; set; }

    [JsonProperty("currenttier")]
    public long Currenttier { get; set; }

    [JsonProperty("currenttier_patched")]
    public string CurrenttierPatched { get; set; }

    [JsonProperty("player_card")]
    public Guid PlayerCard { get; set; }

    [JsonProperty("player_title")]
    public Guid PlayerTitle { get; set; }

    [JsonProperty("party_id")]
    public Guid PartyId { get; set; }

    [JsonProperty("session_playtime")]
    public SessionPlaytime SessionPlaytime { get; set; }

    [JsonProperty("behavior")]
    public Behavior Behavior { get; set; }

    [JsonProperty("platform")]
    public PlatformClass Platform { get; set; }

    [JsonProperty("ability_casts")]
    public AllPlayerAbilityCasts AbilityCasts { get; set; }

    [JsonProperty("assets")]
    public AllPlayerAssets Assets { get; set; }

    [JsonProperty("stats")]
    public Stats Stats { get; set; }

    [JsonProperty("economy")]
    public AllPlayerEconomy Economy { get; set; }

    [JsonProperty("damage_made")]
    public long DamageMade { get; set; }

    [JsonProperty("damage_received")]
    public long DamageReceived { get; set; }
}

public partial class AllPlayerAbilityCasts
{
    [JsonProperty("c_cast")]
    public long CCast { get; set; }

    [JsonProperty("q_cast")]
    public long QCast { get; set; }

    [JsonProperty("e_cast")]
    public long ECast { get; set; }

    [JsonProperty("x_cast")]
    public long XCast { get; set; }
}

public partial class AllPlayerAssets
{
    [JsonProperty("card")]
    public Card Card { get; set; }

    [JsonProperty("agent")]
    public Agent Agent { get; set; }
}

public partial class Agent
{
    [JsonProperty("small")]
    public Uri Small { get; set; }

    [JsonProperty("bust")]
    public Uri Bust { get; set; }

    [JsonProperty("full")]
    public Uri Full { get; set; }

    [JsonProperty("killfeed")]
    public Uri Killfeed { get; set; }
}

public partial class Card
{
    [JsonProperty("small")]
    public Uri Small { get; set; }

    [JsonProperty("large")]
    public Uri Large { get; set; }

    [JsonProperty("wide")]
    public Uri Wide { get; set; }
}

public partial class Behavior
{
    [JsonProperty("afk_rounds")]
    public double AfkRounds { get; set; }

    [JsonProperty("friendly_fire")]
    public FriendlyFire FriendlyFire { get; set; }

    [JsonProperty("rounds_in_spawn")]
    public double RoundsInSpawn { get; set; }
}

public partial class FriendlyFire
{
    [JsonProperty("incoming")]
    public long Incoming { get; set; }

    [JsonProperty("outgoing")]
    public long Outgoing { get; set; }
}

public partial class AllPlayerEconomy
{
    [JsonProperty("spent")]
    public LoadoutValue Spent { get; set; }

    [JsonProperty("loadout_value")]
    public LoadoutValue LoadoutValue { get; set; }
}

public partial class LoadoutValue
{
    [JsonProperty("overall")]
    public long Overall { get; set; }

    [JsonProperty("average")]
    public long Average { get; set; }
}

public partial class PlatformClass
{
    [JsonProperty("type")]
    public string Type { get; set; }

    [JsonProperty("os")]
    public Os Os { get; set; }
}

public partial class Os
{
    [JsonProperty("name")]
    public string Name { get; set; }

    [JsonProperty("version")]
    public Version Version { get; set; }
}

public partial class SessionPlaytime
{
    [JsonProperty("minutes")]
    public long Minutes { get; set; }

    [JsonProperty("seconds")]
    public long Seconds { get; set; }

    [JsonProperty("milliseconds")]
    public long Milliseconds { get; set; }
}

public partial class Stats
{
    [JsonProperty("score")]
    public long Score { get; set; }

    [JsonProperty("kills")]
    public long Kills { get; set; }

    [JsonProperty("deaths")]
    public long Deaths { get; set; }

    [JsonProperty("assists")]
    public long Assists { get; set; }

    [JsonProperty("bodyshots")]
    public long Bodyshots { get; set; }

    [JsonProperty("headshots")]
    public long Headshots { get; set; }

    [JsonProperty("legshots")]
    public long Legshots { get; set; }
}

public partial class Round
{
    [JsonProperty("winning_team")]
    public string WinningTeam { get; set; }

    [JsonProperty("end_type")]
    public string EndType { get; set; }

    [JsonProperty("bomb_planted")]
    public bool BombPlanted { get; set; }

    [JsonProperty("bomb_defused")]
    public bool BombDefused { get; set; }

    [JsonProperty("plant_events")]
    public PlantEvents PlantEvents { get; set; }

    [JsonProperty("defuse_events")]
    public DefuseEvents DefuseEvents { get; set; }

    [JsonProperty("player_stats")]
    public PlayerStat[] PlayerStats { get; set; }
}

public partial class DefuseEvents
{
    [JsonProperty("defuse_location")]
    public Location DefuseLocation { get; set; }

    [JsonProperty("defused_by")]
    public EdBy DefusedBy { get; set; }

    [JsonProperty("defuse_time_in_round")]
    public long? DefuseTimeInRound { get; set; }

    [JsonProperty("player_locations_on_defuse")]
    public PlayerLocationsOn[] PlayerLocationsOnDefuse { get; set; }
}

public partial class EdBy
{
    [JsonProperty("puuid")]
    public Guid Puuid { get; set; }

    [JsonProperty("display_name")]
    public string DisplayName { get; set; }

    [JsonProperty("team")]
    public string Team { get; set; }
}

public partial class PlantEvents
{
    [JsonProperty("plant_location")]
    public Location PlantLocation { get; set; }

    [JsonProperty("planted_by")]
    public EdBy PlantedBy { get; set; }

    [JsonProperty("plant_site")]
    public string? PlantSite { get; set; }

    [JsonProperty("plant_time_in_round")]
    public long? PlantTimeInRound { get; set; }

    [JsonProperty("player_locations_on_plant")]
    public PlayerLocationsOn[] PlayerLocationsOnPlant { get; set; }
}

public partial class PlayerStat
{
    [JsonProperty("ability_casts")]
    public PlayerStatAbilityCasts AbilityCasts { get; set; }

    [JsonProperty("player_puuid")]
    public Guid PlayerPuuid { get; set; }

    [JsonProperty("player_display_name")]
    public string PlayerDisplayName { get; set; }

    [JsonProperty("player_team")]
    public string PlayerTeam { get; set; }

    [JsonProperty("damage_events")]
    public DamageEvent[] DamageEvents { get; set; }

    [JsonProperty("damage")]
    public long Damage { get; set; }

    [JsonProperty("bodyshots")]
    public long Bodyshots { get; set; }

    [JsonProperty("headshots")]
    public long Headshots { get; set; }

    [JsonProperty("legshots")]
    public long Legshots { get; set; }

    [JsonProperty("kill_events")]
    public Kill[] KillEvents { get; set; }

    [JsonProperty("kills")]
    public long Kills { get; set; }

    [JsonProperty("score")]
    public long Score { get; set; }

    [JsonProperty("economy")]
    public PlayerStatEconomy Economy { get; set; }

    [JsonProperty("was_afk")]
    public bool WasAfk { get; set; }

    [JsonProperty("was_penalized")]
    public bool WasPenalized { get; set; }

    [JsonProperty("stayed_in_spawn")]
    public bool StayedInSpawn { get; set; }
}

public partial class PlayerStatAbilityCasts
{
    [JsonProperty("c_casts")]
    public object CCasts { get; set; }

    [JsonProperty("q_casts")]
    public object QCasts { get; set; }

    [JsonProperty("e_cast")]
    public object ECast { get; set; }

    [JsonProperty("x_cast")]
    public object XCast { get; set; }
}

public partial class DamageEvent
{
    [JsonProperty("receiver_puuid")]
    public Guid ReceiverPuuid { get; set; }

    [JsonProperty("receiver_display_name")]
    public string ReceiverDisplayName { get; set; }

    [JsonProperty("receiver_team")]
    public string ReceiverTeam { get; set; }

    [JsonProperty("bodyshots")]
    public long Bodyshots { get; set; }

    [JsonProperty("damage")]
    public long Damage { get; set; }

    [JsonProperty("headshots")]
    public long Headshots { get; set; }

    [JsonProperty("legshots")]
    public long Legshots { get; set; }
}

public partial class PlayerStatEconomy
{
    [JsonProperty("loadout_value")]
    public long LoadoutValue { get; set; }

    [JsonProperty("weapon")]
    public Weapon Weapon { get; set; }

    [JsonProperty("armor")]
    public Armor Armor { get; set; }

    [JsonProperty("remaining")]
    public long Remaining { get; set; }

    [JsonProperty("spent")]
    public long Spent { get; set; }
}

public partial class Armor
{
    [JsonProperty("id")]
    public Guid? Id { get; set; }

    [JsonProperty("name")]
    public string? Name { get; set; }

    [JsonProperty("assets")]
    public ArmorAssets Assets { get; set; }
}

public partial class ArmorAssets
{
    [JsonProperty("display_icon")]
    public Uri DisplayIcon { get; set; }
}

public partial class Weapon
{
    [JsonProperty("id")]
    public Guid? Id { get; set; }

    [JsonProperty("name")]
    public string? Name { get; set; }

    [JsonProperty("assets")]
    public DamageWeaponAssetsClass Assets { get; set; }
}

public partial class Teams
{
    [JsonProperty("red")]
    public Blue Red { get; set; }

    [JsonProperty("blue")]
    public Blue Blue { get; set; }
}

public partial class Blue
{
    [JsonProperty("has_won")]
    public bool HasWon { get; set; }

    [JsonProperty("rounds_won")]
    public long RoundsWon { get; set; }

    [JsonProperty("rounds_lost")]
    public long RoundsLost { get; set; }

    [JsonProperty("roster")]
    public object Roster { get; set; }
}

public partial class MatchResponse
{
    public static MatchResponse FromJson(string json) => JsonConvert.DeserializeObject<MatchResponse>(json, QuickType.Converter.Settings);
}

// public static class Serialize
// {
//     public static string ToJson(this MatchResponse self) => JsonConvert.SerializeObject(self, QuickType.Converter.Settings);
// }

// internal static class Converter
// {
//     public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
//     {
//         MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
//         DateParseHandling = DateParseHandling.None,
//     };
// }